function [ boxes ] = generateProposals( im )
% generateProposals(im) generates bounding boxes proposals for the input
% image 'im' using the Selective Search algorithm.
%
% Inputs:
%
%   - im : Input image.
%   
%
% Outputs:
%
%   - boxes : Nx4 matrix specifying the N bounding boxes generated by
%   Selective Search. Each bounding box is specified as a 1x4 vector
%   [x y w h], where x and y are the coordinates of the top left corner of 
%   the bounding box and w and h specify the height and width of it. Note 
%   that the coordinate system used for x and y is 0-based, meaning that 
%   the topmost left pixel of any image has coordinates (0,0) (not 1,1).
%

    colorTypes = {'Hsv', 'Lab', 'RGI', 'H', 'Intensity'};
    colorType = colorTypes{1}; % Single color space for demo

    % Here you specify which similarity functions to use in merging
    simFunctionHandles = {@SSSimColourTextureSizeFillOrig, @SSSimTextureSizeFill, @SSSimBoxFillOrig, @SSSimSize};
    simFunctionHandles = simFunctionHandles(1:4); % Two different merging strategies

    % Thresholds for the Felzenszwalb and Huttenlocher segmentation algorithm.
    % Note that by default, we set minSize = k, and sigma = 0.8.
    k = 50; % controls size of segments of initial segmentation. 
    minSize = k;
    sigma = 0.3; %0.8

    % Perform Selective Search
    [boxes, ~ , ~, ~] = Image2HierarchicalGrouping(im, sigma, k, minSize, colorType, simFunctionHandles);
    boxes = BoxRemoveDuplicates(boxes);
    
    % Transform the boxes to fast-rcnn convention 
    boxes = boxes(:,[2 1 4 3]);
    boxes = boxes - 1 ;
    

end

